[package]
name = "integration-test"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
rouille = "3.6.1"
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.93"
clap = { version= "4.1.14", features = ["derive"] }
chrono = "0.4.24"
