[package]
name = "integration-test"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
rouille = "3.6.1"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
clap = { version= "4.0.29", features = ["derive"] }
chrono = "0.4.22"
