[package]
name = "integration-test"
edition = "2021"
rust-version = "1.75"

[dependencies]
rouille = "3.6.2"
serde = { version = "1.0.194", features = ["derive"] }
serde_json = "1.0.110"
clap = { version= "4.4.12", features = ["derive"] }
chrono = "0.4.31"
