version: 2.1

executors:
  openjdk-7:
    docker:
      # CircleCI no longer provides OpenJDK 7 images. We use Azul's official image instead.
      - image: azul/zulu-openjdk:7
  openjdk-8:
    docker:
      - image: cimg/openjdk:8.0
  openjdk-11:
    docker:
      - image: cimg/openjdk:11.0

jobs:
  maven:
    parameters:
      executor:
        type: "string"
    executor:
      name: << parameters.executor >>
    steps:
      - run:
          # Azul's images do not ship with git installed
          name: Install git (if necessary)
          command: |
            if ! command -v git; then
              apt-get update
              apt-get install -y git
            fi
      - run:
          # Azul's images do not ship with curl installed
          name: Install curl (if necessary)
          command: |
            if ! command -v curl; then
              apt-get update
              apt-get install -y curl
            fi
      - checkout
      - run: ./mvnw clean install -Pit
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

workflows:
  ci:
    jobs:
      - maven:
          matrix:
            parameters:
              executor: ["openjdk-7", "openjdk-8", "openjdk-11"]
