name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  maven:
    name: "Execute build, run tests (Java ${{ matrix.java-version }})"
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        java-version:
          - 7
          - 8
          - 11
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: ${{ matrix.java-version }}
      - run: "./mvnw --batch-mode clean install -Pit"
